# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c10f587aeadc1da7f44165a6293c810f713f98183c35a44dd5f801a2a547be958165d72e9cdfccc7ca1554d32b7fac14515145a0e4d210c03271971c1be7ef6

test:
  secret_key_base: 2ffd3608e4d8a3047240bd58c6e12703639fea4cb3934521adb2d17bdbe62ad30e0b927c57723ed917e99785c90f55d7b463cb4ec62c84e8748bbc60cbfa9be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
